apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-hosted-rest-api
  description: Hosted REST API
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition: |
    openapi: 3.0.0
    info:
      title: My Hosted REST API
      version: 1.0.0
      description: This is a sample REST API.
    paths:
      /example:
        get:
          summary: Example endpoint
          responses:
            '200':
              description: Successful response
